- build.gradle
- src/main/java/numble/sobunsobun/security/SecurityConfig.java
- src/main/java/numble/sobunsobun/security/WebMvcConfig.java
- src/main/java/numble/sobunsobun/user/UserController.java
- src/main/java/numble/sobunsobun/user/domain/User.java
- src/main/java/numble/sobunsobun/user/dto/JoinDto.java
- src/main/java/numble/sobunsobun/user/dto/LoginDto.java
- src/main/java/numble/sobunsobun/user/repository/UserRepository.java
- src/main/java/numble/sobunsobun/user/service/UserService.java
회원관리 API 구현
1. User Table 구성 완료
2. 회원가입 API 구현 완료
3. 닉네임 중복 확인 API 구현 완료
4. Cors 서버 세팅 완료
5. Spring Security 세팅 완료
6. 로그인 API 구현 완료 (Spring Security 설정 추가 필요)
-
현재는 모든 API가 Spring Security에 영향을 안받도록 해놓음.
로그인 API에 Security 설정 추가를 한 후 교체 요망
-
> 회원관리 API 구현

- src/main/java/numble/sobunsobun/user/UserController.java
- src/main/java/numble/sobunsobun/user/domain/User.java
- src/main/java/numble/sobunsobun/user/dto/JoinDto.java
회원 관리 API 수정(3)
1. 회원 테이블 및 회원가입에 위도 / 경도 정보 추가
2. 회원가입 비밀번호 암호화 추가
-
-
> 회원 관리 API 수정(3)

- src/main/java/numble/sobunsobun/security/SecurityConfig.java
- src/main/java/numble/sobunsobun/security/WebMvcConfig.java
Spring & Spring Security cors 설정 추가
- Spring WebMvcConfig 에 localhost 3000 origin 추가
- Spring SecurityConfig 에 http cors 설정 추가
-
> Spring & Spring Security cors 설정 추가

- src/main/java/numble/sobunsobun/security/SecurityConfig.java
- src/main/java/numble/sobunsobun/security/WebMvcConfig.java
> 🚑️ [HOTFIX] : SPRING SECURITY

- src/main/java/numble/sobunsobun/user/UserController.java
회원 관리 API 구현(3)
- 이메일 중복 확인 API 구현 완료
-
> 회원 관리 API 구현(3)

- src/main/java/numble/sobunsobun/post/PostController.java
- src/main/java/numble/sobunsobun/post/domain/Post.java
- src/main/java/numble/sobunsobun/post/dto/AllPostResponseDto.java
- src/main/java/numble/sobunsobun/post/repository/PostRepository.java
✨ [FEAT] : 전체 게시물 조회 API 구현
1. Post 객체 도메인에 Location Column 추가
2. 카테고리 별 페이징 처리 구현
3. 카테고리 상관없이 ALL 페이징 처리 구현
-
-
> ✨ [FEAT] : 전체 게시물 조회 API 구현

- src/main/java/numble/sobunsobun/post/PostController.java
- src/main/java/numble/sobunsobun/post/dto/AllPostResponseDto.java
📝 [ADD] : allPostResponseDto에 category 추가
-
-
> 📝 [ADD] : allPostResponseDto에 category 추가

- src/main/java/numble/sobunsobun/myPage/MyPageController.java
- src/main/java/numble/sobunsobun/myPage/dto/ModifyNicknameDto.java
마이페이지 API 구현 (2)
- 마이페이지 닉네임 변경 API 추가
-
> 마이페이지 API 구현 (2)

- src/main/java/numble/sobunsobun/like/domain/Like.java
- src/main/java/numble/sobunsobun/like/repository/LikeRepository.java
- src/main/java/numble/sobunsobun/like/service/LikeService.java
- src/main/java/numble/sobunsobun/post/PostController.java
- src/main/java/numble/sobunsobun/post/domain/Post.java
- src/main/java/numble/sobunsobun/post/dto/ModifyPostDto.java
- src/main/java/numble/sobunsobun/post/dto/RegisterPostDto.java
게시글 좋아요 / 좋아요 취소 & 게시글 마켓 주소 컬럼 추가
-
-
> 게시글 좋아요 / 좋아요 취소 & 게시글 마켓 주소 컬럼 추가

- src/main/java/numble/sobunsobun/apply/domain/Apply.java
- src/main/java/numble/sobunsobun/apply/repository/ApplyRepository.java
- src/main/java/numble/sobunsobun/apply/service/ApplyService.java
- src/main/java/numble/sobunsobun/post/PostController.java
- src/main/java/numble/sobunsobun/post/dto/AllPostResponseDto.java
- src/main/java/numble/sobunsobun/post/dto/DetailPostDto.java
- src/main/java/numble/sobunsobun/utils/JwtTokenService.java
게시물 관련 API 수정 및 구현
1. 상세 게시물 조회 API 수정 (필드 추가)
2. 전체 게시물 조회 API 수정 (필드 추가)
3. 게시물 참여 / 참여 취소 API 구현 (모집 관련 예외처리 안함)
4. Access Token 만료 시간 대폭 증가
-
-
> 게시물 관련 API 수정 및 구현

- src/main/java/numble/sobunsobun/childComment/ChildCommentController.java
- src/main/java/numble/sobunsobun/childComment/domain/ChildComment.java
- src/main/java/numble/sobunsobun/childComment/dto/NestedCommentsDto.java
- src/main/java/numble/sobunsobun/childComment/dto/RegisterDto.java
- src/main/java/numble/sobunsobun/childComment/repository/ChildCommentRepository.java
- src/main/java/numble/sobunsobun/childComment/service/ChildCommentService.java
- src/main/java/numble/sobunsobun/parentComment/ParentCommentController.java
- src/main/java/numble/sobunsobun/parentComment/domain/ParentComment.java
- src/main/java/numble/sobunsobun/parentComment/dto/AllCommentsResponse.java
- src/main/java/numble/sobunsobun/parentComment/dto/RegisterDto.java
- src/main/java/numble/sobunsobun/parentComment/repository/ParentCommentRepository.java
- src/main/java/numble/sobunsobun/parentComment/service/ParentCommentService.java
- src/main/java/numble/sobunsobun/security/SecurityConfig.java
- src/main/java/numble/sobunsobun/user/UserController.java
- src/main/java/numble/sobunsobun/user/service/UserService.java
댓글 관련 API
1. 원댓글 작성 API 구현
2. 대댓글 작성 API 구현
3. 전체 댓글 조회 API 구현
-
-
> 댓글 관련 API 구현

- src/main/java/numble/sobunsobun/myPosts/MyPostsController.java
- src/main/java/numble/sobunsobun/myPosts/dto/MyPostDto.java
- src/main/java/numble/sobunsobun/post/repository/PostRepository.java
- src/main/java/numble/sobunsobun/security/SecurityConfig.java
내가 작성한 게시물 관련 API 구현 (1)
- 내가 작성한 게시물 (진행중인 소분) API
-
> 내가 작성한 게시물 관련 API 구현 (1)

- src/main/java/numble/sobunsobun/post/PostController.java
- src/main/java/numble/sobunsobun/post/dto/DetailPostDto.java
게시물 관련 API 수정
1. 게시물 참여 / 참여 취소 API 수정 (모집인원 넘지 못하게)
2. 전체 게시물 조회 API 수정 (작성자 닉네임 수정)
3. 상세 게시물 조회 API 수정 (isLike, isApply 추가)
-
-
> 게시물 관련 API 수정

- src/main/java/numble/sobunsobun/post/PostController.java
- src/main/java/numble/sobunsobun/post/domain/Post.java
- src/main/java/numble/sobunsobun/post/dto/DetailPostDto.java
- src/main/java/numble/sobunsobun/post/repository/PostRepository.java
상세 게시물 조회 API 수정 & 게시물 마감 API 구현
1. 상세 게시물 조회 API 수정
2. 게시물 마감 API 구현
-
-
> 상세 게시물 조회 API 수정 & 게시물 마감 API 구현

- build.gradle
- src/main/java/numble/sobunsobun/myPage/MyPageController.java
- src/main/java/numble/sobunsobun/s3Image/AmazonS3Config.java
- src/main/java/numble/sobunsobun/s3Image/AwsS3Service.java
- src/main/java/numble/sobunsobun/s3Image/CommonUtils.java
- src/main/java/numble/sobunsobun/user/domain/User.java
- src/main/resources/application.properties
> 프로필 사진 변경 API 구현

- src/main/java/numble/sobunsobun/myInfo/MyInfoController.java
- src/main/java/numble/sobunsobun/myInfo/MyInfoDto.java
- src/main/java/numble/sobunsobun/security/SecurityConfig.java
> ✨ [FEAT] : 내 정보 반환 API 구현

- src/main/java/numble/sobunsobun/childComment/dto/NestedCommentsDto.java
- src/main/java/numble/sobunsobun/parentComment/ParentCommentController.java
- src/main/java/numble/sobunsobun/parentComment/dto/AllCommentsResponse.java
🚑️ [HOTFIX] : 전체 댓글 조회 API 수정
-
-
> 🚑️ [HOTFIX] : 전체 댓글 조회 API 수정

- src/main/java/numble/sobunsobun/apply/repository/ApplyRepository.java
- src/main/java/numble/sobunsobun/myPosts/MyPostsController.java
- src/main/java/numble/sobunsobun/myPosts/dto/MyPostDto.java
- src/main/java/numble/sobunsobun/post/repository/PostRepository.java
내 게시물 조회 API 구현
- 내가 작성한 게시물 전체 조회 API (진행중인 소분)
- 내가 작성한 게시물 전체 조회 API (완료된 소분)
-
> 내 게시물 조회 API 구현

- src/main/java/numble/sobunsobun/myLikes/MyLikesController.java
- src/main/java/numble/sobunsobun/myLikes/dto/MyLikesPostDto.java
:truck: [MOVE] : make dto package
-
-
> :truck: [MOVE] : make dto package

- src/main/java/numble/sobunsobun/myLikes/MyLikesController.java
- src/main/java/numble/sobunsobun/myLikes/dto/MyLikesPostDto.java
- src/main/java/numble/sobunsobun/myPosts/MyPostsController.java
- src/main/java/numble/sobunsobun/myPosts/dto/MyPostDto.java
내 게시물 & 관심목록 조회 API 수정
- 내 게시물 (작성게시물 진행중/완료, 참여게시물 진행중/완료) API 4개에서 category 넘겨줌
- 내 관심목록 API 1개에서 category 넘겨줌
-
> 내 게시물 & 관심목록 조회 API 수정

- src/main/java/numble/sobunsobun/childComment/repository/ChildCommentRepository.java
- src/main/java/numble/sobunsobun/parentComment/ParentCommentController.java
- src/main/java/numble/sobunsobun/parentComment/repository/ParentCommentRepository.java
🚑️ [HOTFIX] : 댓글 내림차순 수정
원댓글 / 대댓글 : 내림차순 -> 오름차순 변경
-
-
> 🚑️ [HOTFIX] : 댓글 내림차순 수정

- src/main/java/numble/sobunsobun/post/PostController.java
- src/main/java/numble/sobunsobun/post/dto/DetailPostDto.java
> 상세 게시글 조회 API 수정

- src/main/java/numble/sobunsobun/user/UserController.java
- src/main/java/numble/sobunsobun/user/domain/User.java
🚑️ [HOTFIX] : 회원가입 기본 프로필 이미지 세팅
기본 프로필 이미지 "1"에서 "공룡 이미지 url로 변경"
-
-
> 🚑️ [HOTFIX] : 회원가입 기본 프로필 이미지 세팅

- src/main/java/numble/sobunsobun/post/PostController.java
🚑️ [HOTFIX] : 상세 게시물 조회 API 수정
로그인 사용자의 아이디 반환 -> 게시물 작성자의 닉네임 반환으로 수정
-
-
> 🚑️ [HOTFIX] : 상세 게시물 조회 API 수정

- src/main/java/numble/sobunsobun/myInfo/MyInfoController.java
- src/main/java/numble/sobunsobun/myInfo/MyInfoDto.java
🚑️ [HOTFIX] : 내 정보 반환에 위도, 경도 추가
내 정보 반환 API에 위도, 경도 정보 추가
-
-
> 🚑️ [HOTFIX] : 내 정보 반환에 위도, 경도 추가
